//
// File generated by rootcint at Thu Feb 24 16:50:14 2011

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME eventDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "eventDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void Trigger_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_Trigger(void *p = 0);
   static void *newArray_Trigger(Long_t size, void *p);
   static void delete_Trigger(void *p);
   static void deleteArray_Trigger(void *p);
   static void destruct_Trigger(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Trigger*)
   {
      ::Trigger *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Trigger >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Trigger", ::Trigger::Class_Version(), "./Trigger.h", 12,
                  typeid(::Trigger), DefineBehavior(ptr, ptr),
                  &::Trigger::Dictionary, isa_proxy, 4,
                  sizeof(::Trigger) );
      instance.SetNew(&new_Trigger);
      instance.SetNewArray(&newArray_Trigger);
      instance.SetDelete(&delete_Trigger);
      instance.SetDeleteArray(&deleteArray_Trigger);
      instance.SetDestructor(&destruct_Trigger);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Trigger*)
   {
      return GenerateInitInstanceLocal((::Trigger*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Trigger*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void Detector_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_Detector(void *p = 0);
   static void *newArray_Detector(Long_t size, void *p);
   static void delete_Detector(void *p);
   static void deleteArray_Detector(void *p);
   static void destruct_Detector(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::Detector*)
   {
      ::Detector *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::Detector >(0);
      static ::ROOT::TGenericClassInfo 
         instance("Detector", ::Detector::Class_Version(), "./Detector.h", 20,
                  typeid(::Detector), DefineBehavior(ptr, ptr),
                  &::Detector::Dictionary, isa_proxy, 4,
                  sizeof(::Detector) );
      instance.SetNew(&new_Detector);
      instance.SetNewArray(&newArray_Detector);
      instance.SetDelete(&delete_Detector);
      instance.SetDeleteArray(&deleteArray_Detector);
      instance.SetDestructor(&destruct_Detector);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::Detector*)
   {
      return GenerateInitInstanceLocal((::Detector*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::Detector*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *Trigger::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *Trigger::Class_Name()
{
   return "Trigger";
}

//______________________________________________________________________________
const char *Trigger::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Trigger*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Trigger::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Trigger*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Trigger::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Trigger*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Trigger::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Trigger*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *Detector::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *Detector::Class_Name()
{
   return "Detector";
}

//______________________________________________________________________________
const char *Detector::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Detector*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int Detector::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::Detector*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void Detector::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Detector*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *Detector::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::Detector*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void Detector::Streamer(TBuffer &R__b)
{
   // Stream an object of class Detector.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(Detector::Class(),this);
   } else {
      R__b.WriteClassBuffer(Detector::Class(),this);
   }
}

//______________________________________________________________________________
void Detector::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Detector.
      TClass *R__cl = ::Detector::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nRx", &nRx);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*trigger", &trigger);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nSamples", &nSamples);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "rxpos", (void*)&rxpos);
      R__insp.InspectMember("vector<Position>", (void*)&rxpos, "rxpos.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "waveforms", (void*)&waveforms);
      R__insp.InspectMember("vector<vector<double> >", (void*)&waveforms, "waveforms.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "rxtype", (void*)&rxtype);
      R__insp.InspectMember("vector<int>", (void*)&rxtype, "rxtype.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_Detector(void *p) {
      return  p ? new(p) ::Detector : new ::Detector;
   }
   static void *newArray_Detector(Long_t nElements, void *p) {
      return p ? new(p) ::Detector[nElements] : new ::Detector[nElements];
   }
   // Wrapper around operator delete
   static void delete_Detector(void *p) {
      delete ((::Detector*)p);
   }
   static void deleteArray_Detector(void *p) {
      delete [] ((::Detector*)p);
   }
   static void destruct_Detector(void *p) {
      typedef ::Detector current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::Detector

//______________________________________________________________________________
void Trigger::Streamer(TBuffer &R__b)
{
   // Stream an object of class Trigger.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(Trigger::Class(),this);
   } else {
      R__b.WriteClassBuffer(Trigger::Class(),this);
   }
}

//______________________________________________________________________________
void Trigger::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class Trigger.
      TClass *R__cl = ::Trigger::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "l1Hits", (void*)&l1Hits);
      R__insp.InspectMember("vector<int>", (void*)&l1Hits, "l1Hits.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "l2Hits", (void*)&l2Hits);
      R__insp.InspectMember("vector<int>", (void*)&l2Hits, "l2Hits.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "l3Hits", (void*)&l3Hits);
      R__insp.InspectMember("vector<int>", (void*)&l3Hits, "l3Hits.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nSamples", &nSamples);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "waveforms", (void*)&waveforms);
      R__insp.InspectMember("vector<vector<double> >", (void*)&waveforms, "waveforms.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "threshold", &threshold);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_Trigger(void *p) {
      return  p ? new(p) ::Trigger : new ::Trigger;
   }
   static void *newArray_Trigger(Long_t nElements, void *p) {
      return p ? new(p) ::Trigger[nElements] : new ::Trigger[nElements];
   }
   // Wrapper around operator delete
   static void delete_Trigger(void *p) {
      delete ((::Trigger*)p);
   }
   static void deleteArray_Trigger(void *p) {
      delete [] ((::Trigger*)p);
   }
   static void destruct_Trigger(void *p) {
      typedef ::Trigger current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::Trigger

namespace ROOT {
   void vectorlEPositiongR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEPositiongR_Dictionary();
   static void *new_vectorlEPositiongR(void *p = 0);
   static void *newArray_vectorlEPositiongR(Long_t size, void *p);
   static void delete_vectorlEPositiongR(void *p);
   static void deleteArray_vectorlEPositiongR(void *p);
   static void destruct_vectorlEPositiongR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<Position>*)
   {
      vector<Position> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<Position>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<Position>", -2, "prec_stl/vector", 49,
                  typeid(vector<Position>), DefineBehavior(ptr, ptr),
                  0, &vectorlEPositiongR_Dictionary, isa_proxy, 0,
                  sizeof(vector<Position>) );
      instance.SetNew(&new_vectorlEPositiongR);
      instance.SetNewArray(&newArray_vectorlEPositiongR);
      instance.SetDelete(&delete_vectorlEPositiongR);
      instance.SetDeleteArray(&deleteArray_vectorlEPositiongR);
      instance.SetDestructor(&destruct_vectorlEPositiongR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<Position> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<Position>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEPositiongR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<Position>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEPositiongR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<Position> : new vector<Position>;
   }
   static void *newArray_vectorlEPositiongR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<Position>[nElements] : new vector<Position>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEPositiongR(void *p) {
      delete ((vector<Position>*)p);
   }
   static void deleteArray_vectorlEPositiongR(void *p) {
      delete [] ((vector<Position>*)p);
   }
   static void destruct_vectorlEPositiongR(void *p) {
      typedef vector<Position> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<Position>

namespace ROOT {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<double>

namespace ROOT {
   void vectorlEintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEintgR_Dictionary();
   static void *new_vectorlEintgR(void *p = 0);
   static void *newArray_vectorlEintgR(Long_t size, void *p);
   static void delete_vectorlEintgR(void *p);
   static void deleteArray_vectorlEintgR(void *p);
   static void destruct_vectorlEintgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<int>*)
   {
      vector<int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<int>", -2, "prec_stl/vector", 49,
                  typeid(vector<int>), DefineBehavior(ptr, ptr),
                  0, &vectorlEintgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<int>) );
      instance.SetNew(&new_vectorlEintgR);
      instance.SetNewArray(&newArray_vectorlEintgR);
      instance.SetDelete(&delete_vectorlEintgR);
      instance.SetDeleteArray(&deleteArray_vectorlEintgR);
      instance.SetDestructor(&destruct_vectorlEintgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEintgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<int>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int> : new vector<int>;
   }
   static void *newArray_vectorlEintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<int>[nElements] : new vector<int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEintgR(void *p) {
      delete ((vector<int>*)p);
   }
   static void deleteArray_vectorlEintgR(void *p) {
      delete [] ((vector<int>*)p);
   }
   static void destruct_vectorlEintgR(void *p) {
      typedef vector<int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<int>

namespace ROOT {
   void vectorlEvectorlEdoublegRsPgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEvectorlEdoublegRsPgR_Dictionary();
   static void *new_vectorlEvectorlEdoublegRsPgR(void *p = 0);
   static void *newArray_vectorlEvectorlEdoublegRsPgR(Long_t size, void *p);
   static void delete_vectorlEvectorlEdoublegRsPgR(void *p);
   static void deleteArray_vectorlEvectorlEdoublegRsPgR(void *p);
   static void destruct_vectorlEvectorlEdoublegRsPgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<vector<double> >*)
   {
      vector<vector<double> > *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<vector<double> >),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<vector<double> >", -2, "prec_stl/vector", 49,
                  typeid(vector<vector<double> >), DefineBehavior(ptr, ptr),
                  0, &vectorlEvectorlEdoublegRsPgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<vector<double> >) );
      instance.SetNew(&new_vectorlEvectorlEdoublegRsPgR);
      instance.SetNewArray(&newArray_vectorlEvectorlEdoublegRsPgR);
      instance.SetDelete(&delete_vectorlEvectorlEdoublegRsPgR);
      instance.SetDeleteArray(&deleteArray_vectorlEvectorlEdoublegRsPgR);
      instance.SetDestructor(&destruct_vectorlEvectorlEdoublegRsPgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<vector<double> > >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<vector<double> >*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEvectorlEdoublegRsPgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<vector<double> >*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEvectorlEdoublegRsPgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<vector<double> > : new vector<vector<double> >;
   }
   static void *newArray_vectorlEvectorlEdoublegRsPgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<vector<double> >[nElements] : new vector<vector<double> >[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEvectorlEdoublegRsPgR(void *p) {
      delete ((vector<vector<double> >*)p);
   }
   static void deleteArray_vectorlEvectorlEdoublegRsPgR(void *p) {
      delete [] ((vector<vector<double> >*)p);
   }
   static void destruct_vectorlEvectorlEdoublegRsPgR(void *p) {
      typedef vector<vector<double> > current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<vector<double> >

/********************************************************
* eventDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableeventDict();

extern "C" void G__set_cpp_environmenteventDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("Trigger.h");
  G__add_compiledheader("Detector.h");
  G__cpp_reset_tagtableeventDict();
}
#include <new>
extern "C" int G__cpp_dllreveventDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* Trigger */
static int G__eventDict_161_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Trigger* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Trigger[n];
     } else {
       p = new((void*) gvp) Trigger[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Trigger;
     } else {
       p = new((void*) gvp) Trigger;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__eventDictLN_Trigger));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_161_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Trigger* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new Trigger((int) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) Trigger((int) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__eventDictLN_Trigger));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_161_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Trigger*) G__getstructoffset())->resetTrigger();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_161_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Trigger*) G__getstructoffset())->simulateTrigger((int) G__int(libp->para[0]), *((vector<vector<double> >*) G__int(libp->para[1]))
, (Efficiencies*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_161_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Trigger::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_161_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Trigger::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_161_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Trigger::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_161_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Trigger::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_161_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Trigger*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_161_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Trigger::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_161_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Trigger::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_161_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Trigger::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_161_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Trigger::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__eventDict_161_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Trigger* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Trigger(*(Trigger*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__eventDictLN_Trigger));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Trigger G__TTrigger;
static int G__eventDict_161_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Trigger*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Trigger*) (soff+(sizeof(Trigger)*i)))->~G__TTrigger();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Trigger*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Trigger*) (soff))->~G__TTrigger();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__eventDict_161_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Trigger* dest = (Trigger*) G__getstructoffset();
   *dest = *(Trigger*) libp->para[0].ref;
   const Trigger& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Detector */
static int G__eventDict_173_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Detector* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Detector[n];
     } else {
       p = new((void*) gvp) Detector[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new Detector;
     } else {
       p = new((void*) gvp) Detector;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__eventDictLN_Detector));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_173_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Detector*) G__getstructoffset())->simulateDetector((Event*) G__int(libp->para[0]), (Efficiencies*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_173_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Detector*) G__getstructoffset())->resetDetector();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_173_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((Detector*) G__getstructoffset())->getnRx());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_173_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((Detector*) G__getstructoffset())->getTrigger());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_173_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) Detector::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_173_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Detector::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_173_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) Detector::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_173_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      Detector::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_173_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((Detector*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_173_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Detector::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_173_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Detector::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_173_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) Detector::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__eventDict_173_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) Detector::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__eventDict_173_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   Detector* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new Detector(*(Detector*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__eventDictLN_Detector));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef Detector G__TDetector;
static int G__eventDict_173_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (Detector*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((Detector*) (soff+(sizeof(Detector)*i)))->~G__TDetector();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (Detector*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((Detector*) (soff))->~G__TDetector();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__eventDict_173_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   Detector* dest = (Detector*) G__getstructoffset();
   *dest = *(Detector*) libp->para[0].ref;
   const Detector& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* Trigger */

/* Detector */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunceventDict {
 public:
  G__Sizep2memfunceventDict(): p(&G__Sizep2memfunceventDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunceventDict::*p)();
};

size_t G__get_sizep2memfunceventDict()
{
  G__Sizep2memfunceventDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceeventDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__eventDictLN_Trigger))) {
     Trigger *G__Lderived;
     G__Lderived=(Trigger*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__eventDictLN_Trigger),G__get_linked_tagnum(&G__eventDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__eventDictLN_Detector))) {
     Detector *G__Lderived;
     G__Lderived=(Detector*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__eventDictLN_Detector),G__get_linked_tagnum(&G__eventDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableeventDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__eventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__eventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__eventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__eventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__eventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__eventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__eventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__eventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__eventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__eventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__eventDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__eventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__eventDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__eventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__eventDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G__eventDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__eventDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__eventDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__eventDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__eventDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__eventDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Position>",117,G__get_linked_tagnum(&G__eventDictLN_vectorlEPositioncOallocatorlEPositiongRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__eventDictLN_reverse_iteratorlEvectorlEPositioncOallocatorlEPositiongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__eventDictLN_vectorlEPositioncOallocatorlEPositiongRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__eventDictLN_reverse_iteratorlEvectorlEPositioncOallocatorlEPositiongRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__eventDictLN_vectorlEPositioncOallocatorlEPositiongRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* Trigger */
static void G__setup_memvarTrigger(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__eventDictLN_Trigger));
   { Trigger *p; p=(Trigger*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__eventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"l1Hits=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__eventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"l2Hits=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__eventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"l3Hits=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"nSamples=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__eventDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),G__defined_typename("vector<vector<double> >"),-1,4,"waveforms=",0,"these are the waveforms in the trigger path, different from the waveforms in the signal path used for analysis");
   G__memvar_setup((void*)0,100,0,0,-1,-1,-1,4,"threshold=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__eventDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* Detector */
static void G__setup_memvarDetector(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__eventDictLN_Detector));
   { Detector *p; p=(Detector*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"nRx=",0,"number of antennas");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__eventDictLN_Trigger),-1,-1,4,"trigger=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"nSamples=",0,"number of samples in waveforms for analysis");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__eventDictLN_vectorlEPositioncOallocatorlEPositiongRsPgR),G__defined_typename("vector<Position>"),-1,4,"rxpos=",0,"position of antennas ");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__eventDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),G__defined_typename("vector<vector<double> >"),-1,4,"waveforms=",0,"waveforms for analysis ");
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__eventDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"rxtype=",0,"antenna types (0=dipole, 1=slot) ");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__eventDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvareventDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTrigger(void) {
   /* Trigger */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__eventDictLN_Trigger));
   G__memfunc_setup("l1Trigger",881,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__eventDictLN_vectorlEintcOallocatorlEintgRsPgR), G__defined_typename("vector<int>"), 0, 2, 1, 4, 0, 
"i - - 0 - nRx u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<vector<double> >' 0 - waveforms", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("l2Trigger",882,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__eventDictLN_vectorlEintcOallocatorlEintgRsPgR), G__defined_typename("vector<int>"), 0, 1, 1, 4, 0, "u 'vector<int,allocator<int> >' 'vector<int>' 0 - l1Hits", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("l3Trigger",883,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__eventDictLN_vectorlEintcOallocatorlEintgRsPgR), G__defined_typename("vector<int>"), 0, 1, 1, 4, 0, "u 'vector<int,allocator<int> >' 'vector<int>' 0 - l2Hits", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Trigger",724,G__eventDict_161_0_4, 105, G__get_linked_tagnum(&G__eventDictLN_Trigger), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Trigger",724,G__eventDict_161_0_5, 105, G__get_linked_tagnum(&G__eventDictLN_Trigger), -1, 0, 1, 1, 1, 0, "i - - 0 - nRx", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("resetTrigger",1271,G__eventDict_161_0_6, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("simulateTrigger",1592,G__eventDict_161_0_7, 121, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - nRx u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<vector<double> >' 0 - waveforms "
"U 'Efficiencies' - 0 - efficiencies", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__eventDict_161_0_8, 85, G__get_linked_tagnum(&G__eventDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Trigger::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__eventDict_161_0_9, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Trigger::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__eventDict_161_0_10, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Trigger::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__eventDict_161_0_11, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Trigger::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__eventDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__eventDict_161_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__eventDict_161_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Trigger::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__eventDict_161_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Trigger::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__eventDict_161_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Trigger::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__eventDict_161_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Trigger::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("Trigger", 724, G__eventDict_161_0_20, (int) ('i'), G__get_linked_tagnum(&G__eventDictLN_Trigger), -1, 0, 1, 1, 1, 0, "u 'Trigger' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Trigger", 850, G__eventDict_161_0_21, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__eventDict_161_0_22, (int) ('u'), G__get_linked_tagnum(&G__eventDictLN_Trigger), -1, 1, 1, 1, 1, 0, "u 'Trigger' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncDetector(void) {
   /* Detector */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__eventDictLN_Detector));
   G__memfunc_setup("Detector",826,G__eventDict_173_0_1, 105, G__get_linked_tagnum(&G__eventDictLN_Detector), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("simulateDetector",1694,G__eventDict_173_0_2, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'Event' - 0 - event U 'Efficiencies' - 0 - efficiencies", "simulates the detector response, including the waveforms at each antenna for analysis", (void*) NULL, 0);
   G__memfunc_setup("resetDetector",1373,G__eventDict_173_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getnRx",632,G__eventDict_173_0_4, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getTrigger",1044,G__eventDict_173_0_5, 85, G__get_linked_tagnum(&G__eventDictLN_Trigger), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__eventDict_173_0_6, 85, G__get_linked_tagnum(&G__eventDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&Detector::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__eventDict_173_0_7, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Detector::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__eventDict_173_0_8, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&Detector::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__eventDict_173_0_9, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&Detector::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__eventDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - insp", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__eventDict_173_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__eventDict_173_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Detector::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__eventDict_173_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Detector::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__eventDict_173_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&Detector::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__eventDict_173_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&Detector::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("Detector", 826, G__eventDict_173_0_18, (int) ('i'), G__get_linked_tagnum(&G__eventDictLN_Detector), -1, 0, 1, 1, 1, 0, "u 'Detector' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~Detector", 952, G__eventDict_173_0_19, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__eventDict_173_0_20, (int) ('u'), G__get_linked_tagnum(&G__eventDictLN_Detector), -1, 1, 1, 1, 1, 0, "u 'Detector' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunceventDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globaleventDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funceventDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__eventDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__eventDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__eventDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__eventDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__eventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__eventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__eventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__eventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__eventDictLN_Efficiencies = { "Efficiencies" , 99 , -1 };
G__linked_taginfo G__eventDictLN_Trigger = { "Trigger" , 99 , -1 };
G__linked_taginfo G__eventDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__eventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__eventDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__eventDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__eventDictLN_Event = { "Event" , 99 , -1 };
G__linked_taginfo G__eventDictLN_Detector = { "Detector" , 99 , -1 };
G__linked_taginfo G__eventDictLN_vectorlEPositioncOallocatorlEPositiongRsPgR = { "vector<Position,allocator<Position> >" , 99 , -1 };
G__linked_taginfo G__eventDictLN_reverse_iteratorlEvectorlEPositioncOallocatorlEPositiongRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Position,allocator<Position> >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableeventDict() {
  G__eventDictLN_TClass.tagnum = -1 ;
  G__eventDictLN_TBuffer.tagnum = -1 ;
  G__eventDictLN_TMemberInspector.tagnum = -1 ;
  G__eventDictLN_TObject.tagnum = -1 ;
  G__eventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__eventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__eventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__eventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__eventDictLN_Efficiencies.tagnum = -1 ;
  G__eventDictLN_Trigger.tagnum = -1 ;
  G__eventDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__eventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__eventDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__eventDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__eventDictLN_Event.tagnum = -1 ;
  G__eventDictLN_Detector.tagnum = -1 ;
  G__eventDictLN_vectorlEPositioncOallocatorlEPositiongRsPgR.tagnum = -1 ;
  G__eventDictLN_reverse_iteratorlEvectorlEPositioncOallocatorlEPositiongRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableeventDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__eventDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__eventDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__eventDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__eventDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__eventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__eventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__eventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__eventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__eventDictLN_Efficiencies);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__eventDictLN_Trigger),sizeof(Trigger),-1,323840,(char*)NULL,G__setup_memvarTrigger,G__setup_memfuncTrigger);
   G__get_linked_tagnum_fwd(&G__eventDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__eventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__eventDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__eventDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__eventDictLN_Event);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__eventDictLN_Detector),sizeof(Detector),-1,292096,(char*)NULL,G__setup_memvarDetector,G__setup_memfuncDetector);
   G__get_linked_tagnum_fwd(&G__eventDictLN_vectorlEPositioncOallocatorlEPositiongRsPgR);
   G__get_linked_tagnum_fwd(&G__eventDictLN_reverse_iteratorlEvectorlEPositioncOallocatorlEPositiongRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupeventDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupeventDict()");
  G__set_cpp_environmenteventDict();
  G__cpp_setup_tagtableeventDict();

  G__cpp_setup_inheritanceeventDict();

  G__cpp_setup_typetableeventDict();

  G__cpp_setup_memvareventDict();

  G__cpp_setup_memfunceventDict();
  G__cpp_setup_globaleventDict();
  G__cpp_setup_funceventDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunceventDict();
  return;
}
class G__cpp_setup_initeventDict {
  public:
    G__cpp_setup_initeventDict() { G__add_setup_func("eventDict",(G__incsetup)(&G__cpp_setupeventDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initeventDict() { G__remove_setup_func("eventDict"); }
};
G__cpp_setup_initeventDict G__cpp_setup_initializereventDict;

