/********************************************************************
* eventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error eventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableeventDict();
extern void G__cpp_setup_inheritanceeventDict();
extern void G__cpp_setup_typetableeventDict();
extern void G__cpp_setup_memvareventDict();
extern void G__cpp_setup_globaleventDict();
extern void G__cpp_setup_memfunceventDict();
extern void G__cpp_setup_funceventDict();
extern void G__set_cpp_environmenteventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Trigger.h"
#include "Detector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__eventDictLN_TClass;
extern G__linked_taginfo G__eventDictLN_TBuffer;
extern G__linked_taginfo G__eventDictLN_TMemberInspector;
extern G__linked_taginfo G__eventDictLN_TObject;
extern G__linked_taginfo G__eventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__eventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__eventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventDictLN_Efficiencies;
extern G__linked_taginfo G__eventDictLN_Trigger;
extern G__linked_taginfo G__eventDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__eventDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__eventDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__eventDictLN_Event;
extern G__linked_taginfo G__eventDictLN_Detector;
extern G__linked_taginfo G__eventDictLN_vectorlEPositioncOallocatorlEPositiongRsPgR;
extern G__linked_taginfo G__eventDictLN_reverse_iteratorlEvectorlEPositioncOallocatorlEPositiongRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
